# Generated by Django 6.0.4 on 2026-05-08 19:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availabilityId', models.AutoField(primary_key=True, serialize=False)),
                ('dayOfWeek', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('isRecurring', models.BooleanField(default=True)),
                ('recurringEndDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'availabilities',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('passwordHash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientId', models.AutoField(primary_key=True, serialize=False)),
                ('preferredLearnerName', models.CharField(blank=True, max_length=50)),
                ('relationshipToLearner', models.CharField(blank=True, max_length=50)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('scheduledDateTime', models.DateTimeField()),
                ('durationMinutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('availabilityId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tutorLinkApp.availability')),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tutorLinkApp.client')),
                ('locationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tutorLinkApp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
                ('receiverUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('senderUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sentAt'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='processed', max_length=20)),
                ('method', models.CharField(max_length=50)),
                ('processedAt', models.DateTimeField(auto_now_add=True)),
                ('bookingID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tutorLinkApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('reviewDate', models.DateField(auto_now_add=True)),
                ('bookingID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='tutorLinkApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutorId', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('serviceRadiusMiles', models.PositiveIntegerField(default=10)),
                ('isVerified', models.BooleanField(default=False)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('credentialId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('issuingInstitution', models.CharField(max_length=255)),
                ('documentURL', models.URLField(blank=True)),
                ('issueDate', models.DateField()),
                ('tutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='tutorLinkApp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('checkId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(max_length=255)),
                ('dateCompleted', models.DateField(blank=True, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='tutorLinkApp.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='tutorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tutorLinkApp.tutor'),
        ),
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('TutorSubjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ratePerHour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('skillLevel', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('subjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_subjects', to='tutorLinkApp.subject')),
                ('tutorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_subjects', to='tutorLinkApp.tutor')),
            ],
            options={
                'unique_together': {('tutorID', 'subjectID')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='tutorSubjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tutorLinkApp.tutorsubject'),
        ),
    ]
